"""empty message

Revision ID: 4545a4f2f664
Revises: 76615f4a2415
Create Date: 2022-09-08 17:21:23.122119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4545a4f2f664'
down_revision = '76615f4a2415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Bills_user_full_name_Users'), 'Users', ['user_full_name'], ['Vardas ir pavardė'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Bills_user_full_name_Users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_full_name'], ['id'])

    # ### end Alembic commands ###
