"""empty message

Revision ID: b84890109ac8
Revises: 4545a4f2f664
Create Date: 2022-09-09 14:08:27.788196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84890109ac8'
down_revision = '4545a4f2f664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups_id', sa.String(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Bills_groups_id_Groups'), 'Groups', ['groups_id'], ['id'])
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_Bills_groups_id_Groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Groups', ['group_id'], ['id'])
        batch_op.drop_column('groups_id')

    # ### end Alembic commands ###
